spring.application.name=neitindia

#mysql-connection
spring.datasource.url=jdbc:mysql://localhost:3306/neitindia
spring.datasource.username=neituser
spring.datasource.password=neitpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.main.allow-bean-definition-overriding=true

#logging.level.com.neit.india.service=DEBUG
#logging.level.root=DEBUG

# Allow larger file uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Optional: increase file count limit
spring.servlet.multipart.file-size-threshold=2MB

# Session timeout
server.servlet.session.timeout=10m

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alampnm01@gmail.com
spring.mail.password=nbdr cehi fxby iwib
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true